import { ArrowRight } from 'lucide-react';
import Button from '../ui/Button';
import AnimateOnScroll from '../ui/AnimateOnScroll';

export default function CTABanner() {
  return (
    <section className="py-20 relative overflow-hidden canvas-grid">
      <div className="absolute inset-0 pointer-events-none" aria-hidden="true">
        <div className="absolute top-8 left-[10%] w-28 h-24 sticky-note bg-sticky-teal rotate-[-3deg] opacity-70 p-3 hidden sm:block">
          <p className="text-[10px] font-display font-bold uppercase text-ink/50">Pillars</p>
        </div>
        <div className="absolute bottom-10 right-[12%] w-28 h-24 sticky-note bg-sticky-coral rotate-[2deg] opacity-70 p-3 hidden sm:block">
          <p className="text-[10px] font-display font-bold uppercase text-ink/50">Briefs</p>
        </div>
      </div>

      <div className="relative max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
        <AnimateOnScroll>
          <h2 className="text-3xl md:text-4xl font-bold font-display text-ink mb-4">
            Ready to put strategy on the board?
          </h2>
          <p className="text-lg text-ink-soft leading-relaxed mb-8 max-w-2xl mx-auto">
            Join marketing teams who plan content on a shared canvas — pillars,
            calendars, and briefs generated by AI, refined by humans.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <Button href="/#demo" size="lg" variant="primary">
              Try Strategy Canvas
              <ArrowRight className="ml-2 w-5 h-5" />
            </Button>
            <Button href="/pricing" size="lg" variant="secondary">
              View Pricing
            </Button>
          </div>
        </AnimateOnScroll>
      </div>
    </section>
  );
}
